apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
