apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: default
spec:
  selector:
    app: cart-service
  ports:
    - port: 8082
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
