apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  selector:
    app: customer-service
  ports:
    - port: 8083
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
