apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - name: grafana-3001
      port: 3001
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
