apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: order-service
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
