apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  selector:
    app: product-service
  ports:
    - port: 9001
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
