apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ghcr.io/radovan85/ecommerce/eureka-server:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
