apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z postgres 5432;
              do echo waiting for postgres; sleep 2; done
        - name: wait-for-eureka
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z eureka-server 8761;
              do echo waiting for eureka; sleep 2; done
        - name: wait-for-nats
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z nats 4222;
              do echo waiting for nats; sleep 2; done
      containers:
        - name: order-service
          image: ghcr.io/radovan85/order-service:dev3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/ecommerce-db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1111"
            - name: NATS_URL
              value: nats://nats:4222
            - name: SERVICE_NAME
              value: order-service
            - name: EUREKA_URL
              value: http://eureka-server:8761/eureka
            - name: PLAY_SECRET
              value: NpbOJnFle1GUPvnFVPwLkrOgrD`a^R2xO6U<D@:Q>@vcDD<[j9c4yZr^w6Hz`yqo
            - name: PLAY_SERVER_HTTP_PORT
              value: "9000"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5
